### ISSUE TITLE
KV stored using the CLI is not displayed in the UI

### ISSUE THREAD

**Issue by fmorency** [liftedinit/gwen#40]
1. Write a value to the kvstore using some identity
```shell
$ kvstore --pem id2.pem https://alpha-testnet.liftedinit.tech/api/kvstore put mykey somevalue
```
2. Verify the value has been written
```shell
$ kvstore https://alpha-testnet.liftedinit.tech/api/kvstore get mykey
somevalue%
```
3. Open Gwen. Make sure the KVSTORE endpoint is correct
![2023-03-27_11-53](https://user-images.githubusercontent.com/1102868/227995746-02497b1f-ccfb-40fb-a2fe-2b642a57514c.png)

4. Notice that the new KV pair is not listed in the UI
![2023-03-27_11-54](https://user-images.githubusercontent.com/1102868/227995987-f8914b81-8b62-4f39-817f-ba74e3e3db7d.png)

**Comment by stanleyjones** [comment]
This issue was addressed by #52. Closing.
