### ISSUE TITLE
Allow token owner to mint/burn via a UI

### ISSUE THREAD

**Issue by fmorency** [liftedinit/gwen#43]
Description: Only the Token Authority is able to mint/burn at the moment. Allow a token owner to mint/burn the token via UI.

Relates to liftedinit/many-rs#372

As a token owner, I want to be able to mint/burn my token via a UI so that it is easy to manage.

- [x] Should be able to mint/burn tokens as a token owner via Gwen.
- [x] Should NOT be able to mint/burn tokens if not a token owner.
- [x] Should be demoed.

**Comment by stanleyjones** [comment]
See https://github.com/liftedinit/gwen/pull/45
