### ISSUE TITLE
Update Gwen packages & node version

### ISSUE THREAD

**Issue by fmorency** [liftedinit/gwen#56]
We are still on 16.10, causing an issue with some Web3Auth nested dependencies.

**Comment by stanleyjones** [comment]
@fmorency Can you share more about the Web3Auth nested dependencies? I'm not sure if #57 resolved this issue or if I need to upgrade Web3Auth as well.

**Comment by fmorency** [comment]
#57 resolved it, it wouldn't work otherwise. I can't remember the specifics, but Gwen wasn't even starting on 16.10.1 with the updated Web3Auth.
