### ISSUE TITLE
Unable to list Ledger info

### ISSUE THREAD

**Issue by fmorency** [liftedinit/gwen#69]
One is stuck in an infinite loop when creating a new HSM account. The same is happening when importing said HSM account and displaying the Ledger info.

@stanleyjones

**Comment by stanleyjones** [comment]
Will investigate today.

**Comment by stanleyjones** [comment]
I couldn't reproduce this using (Arc)[https://arc.net/] and a Trezor (Model-T)[https://trezor.io/trezor-model-t]. The following steps worked for me:

1. Navigate to gwen.liftedinit.app.
2. Select "Add Account" from the account dropdown.
3. Select "Hardware Authenticator."
4. Plug in hardware authenticator and click "Authorize."
5. Select "USB Security Key" from the browser modal.
6. Confirm on the authenticator.
7. Click "Allow" in the browser modal.
8. Give the account a name in Gwen.
9. Confirm on the authenticator.
10. Receive recovery phrase in Gwen.

Where do you get stuck?

**Comment by fmorency** [comment]
@stanleyjones I'm unable to reproduce as well, but something else is wrong.

Try listing the Ledger info.

I can reproduce on both [Gwen](https://gwen.liftedinit.app) and [QA-Gwen](https://qa-gwen.liftedinit.tech).

**Comment by stanleyjones** [comment]
Are you getting prompted over and over again? It's probably asking once to sign the request to get all of the tokens and then again to get the detailed info for each one. We solved this in Alberto by keeping references to both an anonymous and a signed network. We could do that here too.

**Comment by fmorency** [comment]
> Are you getting prompted over and over again? It's probably asking once to sign the request to get all of the tokens and then again to get the detailed info for each one. We solved this in Alberto by keeping references to both an anonymous and a signed network. We could do that here too.

Yes, and at some point, it just displays a white page. Something crashes.
